<?php

/**
 * @file
 * Primary module hooks for Block API module.
 */

use Drupal\Core\Url;

/**
 * Alter the user login form to redirect the current user.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @return void
 */
function alter_login_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state)
{
  $response = Url::fromUri('http://module_dev.com/custom-welcome-page');
  $form_state->setRedirectUrl($response);
}

/**
 * Implements hook_form_alter().
 */
function block_api_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  switch ($form_id) {
    case 'user_login_form':
      $form['#submit'][] = 'alter_login_form_submit';
      break;
  }
}

/**
 * Impelemented hook_theme()
 */
function block_api_theme($existing, $type, $theme, $path) {
  return [
    'flagship_program' => [
      'template' => 'flagship-program',
      'path' => $path . '/templates',
      'variables' => [
        'data' => null,
      ],
    ],
  ];
}