<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;

/**
 * implements hook_node_view.
 */
function custom_menu_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityTypeId() == "node" && $entity->bundle() == "movie") {
    $node = Node::load($entity->id());
    // Price of the current movie
    $price = (float)$node->get('movie_price')->value;
    $node_response = comparePrice($price);
    // Setting response for the render page.
    $build['my_additional_field'] = [
      '#type' => 'inline_template',
      '#template' => '<div class="py-2 text-primary">{{ response }}</div>',
      '#context' => [
        'response' => $node_response,
      ]  
    ];
  }
}

/**
 * Checks price of the current movie with the budget Friendly movie price and
 * return text response.
 * 
 * @param float $price
 *   Price of the current movie.
 */
function comparePrice(float $price): string {
  $config = \Drupal::configFactory()->getEditable('budget_movie_amount.settings');
  $budget_price = (float)$config->get('budget_amount');

  if ($budget_price > $price) {
    return "The movie is under budget";
  }
  else if ($budget_price == $price) {
    return "The movie is within budget";
  }
  return "The movie is over budget.";
}