# Schema for the configuration files of the custom_otll_form module.
custom_otll_form.settings:
  type: config_object
  label: 'custom_otll_form settings'
  mapping:
    example:
      type: string
      label: 'Example'
