<?php

/**
 * @file
 * Hooks Example module.
 */

/**
 * Implement hook_cron().
 */
function mymodule_cron() {
	\Drupal::messenger()->addMessage("Hello from mymodule hook cron");
}

/**
 * Implement hook_forms_altar().
 */
function mymodule_form_alter(&$form,\Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	\drupal::messenger()->addMessage(t("form_id of this form is @id: ",['@id' => &$form_id]));
	if ($form_id == 'node_article_edit_form') {
		$form['actions']['submit']['#value'] = ('You Wanna Save this article');
	}
	elseif ($form_id == 'node_article_form') {
		$form['actions']['submit']['#value'] = ('Really You Wanna Save this article');
	}
}
